### PR TITLE
Renewed support for Baffin personality

### PR DESCRIPTION
**Pull request by FricoRico**
These changes add new support for Baffin personalities. Since Mac OS 10.12.2 the Baffin support is managed by the AMDRadeonX4100.kext instead of the AMDRadeonX4000.kext. I've tested this on my Akitio Thunder 2 with AMD RX480 setup, I noticed the whoosh during startup but could not finish booting into Mac OS.

Could you confirm this works for you @goalque? Hope you are happy with the changes! 👍

### CODE REVIEW

**Comment by FricoRico** [comment]
I noticed some spacing issues after having saved the file from Xcode, will fix the indentation asap.

**Comment by FricoRico** [comment]
I can now confirm that the RX480 is working under Mac OS 10.12.2. AMD also fixed the power issues under Mac OS since the new Kext updates. Cleaning the kext-cache one more time, that booting into Mac with eGPU unplugged then plugging in eGPU and rebooting one more time fixed my issues.

**Comment by cronos45** [comment]
Does it work with 980 cards on Sierra yet?

**Comment by FricoRico** [comment]
@cronos45 I do not have any so I wouldn't know. These changes are merely my personal changes that I have made and want to share with @goalque.

For now it remains uncertain if the changes will be accepted due to the license restrictions on his repository. If you want GTX980 support I suggest you get creative yourself, as @goalque is not supporting the development of his automated script anymore.

**Comment by FricoRico** [comment]
@goalque I fixed the indentation spacing issues. Let me know if you like the changes.

**Comment by goalque** [comment]
The v0.9.9 cannot be developed further unless I change the license condition:

1. You are free to copy the script for personal use.
    If you make changes, you are not permitted to distribute the script in any way.

https://github.com/goalque/automate-eGPU/blob/master/SCRIPT-LICENSE.txt

**Pull request closed without merging**
